name: Build n Release

on:
    workflow_dispatch:

jobs:
    bnr:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up CMake
              uses: lukka/get-cmake@latest

            - name: Install GCC
              run: choco install mingw

            - name: Install GitHub CLI
              run: choco install gh

            - name: Extract Version
              id: extract_version
              run: |
                  $version = Select-String -Path CMakeLists.txt -Pattern 'VERSION (\d+\.\d+\.\d+)' | ForEach-Object { $_.Matches.Groups[1].Value }
                  echo "VERSION=$version" >> $env:GITHUB_ENV

            - name: Configure CMake
              run: cmake -S . -B build -G "MinGW Makefiles"

            - name: Build
              run: cmake --build build --config Release

            - name: Delete Old
              env:
                  GH_TOKEN: ${{ secrets.PAT }}
              run: |
                  gh auth login --with-token <<< $GH_TOKEN
                  gh release delete v${{ env.VERSION }} -y || true
                  git tag -d v${{ env.VERSION }} || true
                  git push --delete origin v${{ env.VERSION }} || true

            - name: Create Release
              id: create_release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./build/naris.exe
                  tag_name: v${{ env.VERSION }}
                  draft: false
                  prerelease: false
                  token: ${{ secrets.PAT }}
