name: Build n Release

on:
    workflow_dispatch:

jobs:
    bnr:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up CMake
              uses: lukka/get-cmake@latest

            - name: Install GCC
              run: choco install mingw

            - name: Install GitHub CLI
              run: choco install gh

            - name: Extract Version
              run: |
                  $version = Select-String -Path CMakeLists.txt -Pattern 'VERSION (\d+\.\d+\.\d+)' | ForEach-Object { $_.Matches.Groups[1].Value }
                  echo "VERSION=$version" >> $env:GITHUB_ENV

            - name: Configure CMake
              run: cmake -S . -B build -G "MinGW Makefiles"

            - name: Build
              run: cmake --build build --config Release

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: ./build/naris.exe
                  tag_name: v${{ env.VERSION }}
                  draft: false
                  prerelease: false
                  token: ${{ secrets.PAT }}
